apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels: 
        app: backend
    spec:
      containers:
      - name: chatapp-backend
        image: avinashlamichhane01123546/chatapp-backend:latest
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          value: "mongodb://mongo:27017/kurakani"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chatapp-secrets
              key: jwt-secret
        - name: ACCESS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: chatapp-secrets
              key: access-secret-key
        - name: REFRESH_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: chatapp-secrets
              key: refresh-secret-key
        - name: PORT
          value: "5001"
