apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chat-app
type: Opaque
data:
  # JWT secret for authentication
  jwt-secret: YW5zam5kam5qZXdjamNq  # base64 encoded "ansjndjnjewjcjc"
  
  # Access and refresh tokens
  access-secret-key: eW91cl9hY2Nlc3Nfc2VjcmV0X2tleV9oZXJl  # base64 encoded "your_access_secret_key_here"
  refresh-secret-key: eW91cl9yZWZyZXNoX3NlY3JldF9rZXlfaGVyZQ==  # base64 encoded "your_refresh_secret_key_here"